
def XYZ2XYZ(XYZ, nfirst, refFirst, refSecond, dist_ratio):
  data = readXYZ(XYZ)
  atoms = data[0]
  coord = data[1]
  coord_1 = coord[:nfirst]
  coord_2 = coord[nfirst:]
  coord = f_translate(coord_1, coord_2, refFirst, refSecond, dist_ratio)
  ratio = str("%.02f"%dist_ratio)
  print("You are doing distance "+ratio)
  oFile = open(XYZ.split(".")[0]+"_%s.xyz"%ratio,"w")
  oFile.write("%3s\n#Generated by chemFileConvert.py\n"%len(atoms))
  for i in range(len(atoms)):
    oFile.write("%3s   %14.7f%14.7f%14.7f\n"%(atoms[i], coord[i][0], coord[i][1], coord[i][2]))
  oFile.close()
  return True

