
#===================================
#        Chengwen Liu              #
#      liuchw2010@gmail.com        #
#   University of Texas at Austin  #
#===================================

def writeXYZ(fname, atoms, coords):
  if len(atoms) != len(coords):
    print("Error: Number of atoms and coordinate are different")
  else:
    with open(fname, 'w') as fout:
      fout.write("%3s\n#Generated by chemFileConvert.py\n"%len(coords))
      for atom, coord in zip(atoms, coords):
        fout.write("%3s   %14.7f%14.7f%14.7f\n"%(atom, coord[0], coord[1], coord[2]))
  return
    
  
def writeTXYZ(fname, orders, atoms, coords, types, connections):
  with open(fname, 'w') as fout:
    fout.write("%3s #Generated by chemFileConvert.py\n"%len(atoms))
    for od, at, co, ty, con in zip(orders, atoms, coords, types, connections):
      print(od,at,co,ty,con)
      if len(con) == 0:
        fout.write("%6s%3s%14.7f%14.7f%14.7f%6s\n"%(od,at,co[0],co[1],co[2],ty))
      if len(con) == 1:
        fout.write("%6s%3s%14.7f%14.7f%14.7f%6s%3s\n"%(od,at,co[0],co[1],co[2],ty,con[0]))
      if len(con) == 2:
        fout.write("%6s%3s%14.7f%14.7f%14.7f%6s%3s%3s\n"%(od,at,co[0],co[1],co[2],ty,con[0],con[1]))
      if len(con) == 3:
        fout.write("%6s%3s%14.7f%14.7f%14.7f%14.7f%14.7f%6s%3s%3s%3s\n"%(od,at,co[0],co[1],co[2],ty,con[0],con[1],con[2]))
      if len(con) == 4:
        fout.write("%6s%3s"+3*"%14.7f"+"%6s%3s%3s%3s%3s\n"%(od,at,co[0],co[1],co[2],ty,con[0],con[1],con[2],con[3]))
