

#===================================
#        Chengwen Liu              #
#      liuchw2010@gmail.com        #
#   University of Texas at Austin  #
#===================================


import argparse
import numpy as np
import os
from scipy.optimize import minimize 

''' connect two fragments together through covalent bond, initially used to generate Modified RNA structures'''

def readXYZ(xyz):
  atoms  = np.loadtxt(xyz, usecols=(0,), dtype='str', unpack=True, skiprows=2)
  coords = np.loadtxt(xyz, usecols=(1,2,3), dtype='float', unpack=False, skiprows=2)
  return atoms,coords

def distance(coord1, coord2):
  coord1 = np.array(coord1)
  coord2 = np.array(coord2)
  dist = np.sqrt(np.square(coord1-coord2).sum()) 
  return dist

def rotMatrix(axis, theta):
  axis = np.asarray(axis)
  axis = axis/np.sqrt(np.dot(axis, axis))
  a = np.cos(theta/2.0)
  b, c, d = -axis*np.sin(theta/2.0)
  aa, bb, cc, dd = a*a, b*b, c*c, d*d
  bc, ad, ac, ab, bd, cd = b*c, a*d, a*c, a*b, b*d, c*d
  rotmat = np.array([[aa+bb-cc-dd, 2.0*(bc+ad), 2.0*(bd-ac)],
                     [2.0*(bc-ad), aa+cc-bb-dd, 2.0*(cd+ab)],
                     [2.0*(bd+ac), 2.0*(cd-ab), aa+dd-bb-cc]])
  return rotmat

def optimize(atoms1, atoms2, coords1, coords2, p1, p2, dist, dimer):
  '''cost function of distance summation'''
  def costfunc(params):
    func = 0.0
    axis = np.array(params[:3])
    theta = params[3] 
    rotmat = rotMatrix(axis, theta)
    coords2_r = []
    for n in range(len(coords2)):
      coord2_r = np.dot(rotmat, coords2[n]) 
      coords2_r.append(coord2_r)
    coords2_r = np.array(coords2_r)
    distsum = 0.0
    for i in range(len(coords1)):
      for j in range(len(coords2_r)):
        if (i!=p1) and (j!=p2):
          distsum += (distance(coords1[i], coords2_r[j]))
    distp1p2 = distance(coords1[p1], coords2_r[p2])
    func = -(distp1p2)**2 + distsum
    return func

  ''' do the optimization to find the best parameters'''
  x0 = np.array([0.5, 0.5, 0.5, 0.5])
  ret = minimize(costfunc, x0, method='SLSQP', bounds=([-1., 1.],[-1., 1.],[-1., 1.],[0, 6.28319]),options={'disp': True, 'eps': 1.e-4, 'maxiter': 1000, 'ftol': 1e-4})
  np.savetxt("p0.txt", ret.x,fmt='%15.10f')
   
  # optimized parameters 
  axis = np.array(ret.x[:3])
  theta = ret.x[3] 
  
  # get the rotated coordinate
  rotmat = rotMatrix(axis, theta)
  coords2_r = []
  for n in range(len(coords2)):
    coord2_r = np.dot(rotmat, coords2[n]) 
    coords2_r.append(coord2_r)
  coords2_r = np.array(coords2_r)

  # get the rotated then translated coordinate
  tempvec = coords2_r[p2] - coords1[p1]
  transvec = dist*(tempvec)/np.linalg.norm(tempvec)-tempvec
  coords2_rt = []
  for n in range(len(coords2_r)):
    coord2_r = coords2_r[n] + transvec
    coords2_rt.append(coord2_r)
  coords2_rt = np.array(coords2_rt) 
 
  # write the result
  with open(dimer, "w") as f:
    f.write("%s\n" %(len(atoms1) + len(atoms2)))
    f.write("Generated by lbuildcovalent.py\n")
    for i in range(len(atoms1)):
      f.write("%3s %12.5f%12.5f%12.5f\n"%(atoms1[i], coords1[i][0], coords1[i][1], coords1[i][2]))
    for i in range(len(atoms2)):
      f.write("%3s %12.5f%12.5f%12.5f\n"%(atoms2[i], coords2_rt[i][0], coords2_rt[i][1], coords2_rt[i][2]))
  return 

def main():
  parser = argparse.ArgumentParser()
  parser.add_argument('-frag1', dest = 'fragment1', required=True, help="The first fragment in xyz format")  
  parser.add_argument('-frag2', dest = 'fragment2', required=True, help="The second fragment in xyz format")
  parser.add_argument('-indx1', dest = 'atomindex1', required=True, help="The atom index of the first fragment", type=int)  
  parser.add_argument('-indx2', dest = 'atomindex2', required=True, help="The atom index of the second fragment", type=int)
  args = vars(parser.parse_args())

  frag1 = args["fragment1"]
  frag2 = args["fragment2"]
  indx1 = args["atomindex1"] - 1
  indx2 = args["atomindex2"] - 1
  
  atoms1, coords1 = readXYZ(frag1)
  atoms2, coords2 = readXYZ(frag2)
  a1 = atoms1[indx1]
  a2 = atoms2[indx2]
  dist = 1.5 
  dimer = frag1[:-4] + "-" + frag2[:-4] + ".xyz"
  optimize(atoms1, atoms2, coords1, coords2, indx1, indx2, dist, dimer)
  return

if __name__ == "__main__":
  main()
